services:
  web:
    container_name: web
    build: .
    command: "gunicorn config.wsgi:application -c ./config/gunicorn_conf.py"
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - main
    depends_on:
      - postgres
    volumes:
      - ".:/src"
    restart: "always"

  postgres:
    image : "postgres:18"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_DB : ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - main
    restart: "always"

  nginx :
    container_name : nginx
    command: nginx -g 'daemon off;'
    image : "nginx:1.29.4"
    ports :
      - "80:80"
      - "443:443"
    volumes:
      - "./static/:/src/static"
      - "./media/:/src/media"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

    networks:
      - main
    depends_on:
      - web
    restart: always


networks:
  main:

volumes:
  postgres_data:
